import type { AppConfig, DaoConfig } from "@bigmarket/bm-types";

export const appConfigByNetwork: Record<string, AppConfig> = {
  devnet: {
    VITE_PUBLIC_APP_NAME: "BigMarket",
    VITE_PUBLIC_APP_VERSION: "1.0.0",
    VITE_NETWORK: "devnet",
    VITE_BIGMARKET_API: "http://localhost:3020/bigmarket-api",
    VITE_BIGMARKET_WS: "http://localhost:3020/bigmarket-api/ws",
    VITE_SUI_API: "http://localhost:9001",
    VITE_FORUM_API: "http://localhost:3025/forum-api",
    VITE_STACKS_API: "http://localhost:3999",
    VITE_STACKS_EXPLORER: "http://localhost:8000",
    VITE_MEMPOOL_API: "http://localhost:8001",
    VITE_POLL_PAYMENT_USTX: 50000000,
    VITE_BITCOIN_WALLET: "bcrt1q4zymxl8934vvle2ppzw0j6tkwz3d7qw4f0esme",
    VITE_CLARITY_BITCOIN:
      "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.clarity-bitcoin-lib-v5",
    VITE_WALLET_CONNECT_PROJECT_ID: "085d52703daed2198b4dbc2cd815951f",
  },
  testnet: {
    VITE_PUBLIC_APP_NAME: "BigMarket",
    VITE_PUBLIC_APP_VERSION: "1.0.0",
    VITE_NETWORK: "testnet",
    VITE_BIGMARKET_API: "https://api.testnet.bigmarket.ai/bigmarket-api",
    //VITE_BIGMARKET_API: 'http://localhost:3020/bigmarket-api',
    VITE_BIGMARKET_WS: "https://api.testnet.bigmarket.ai/bigmarket-api/ws",
    VITE_STACKS_API: "https://api.testnet.hiro.so",
    VITE_STACKS_EXPLORER: "https://explorer.hiro.so",
    VITE_FORUM_API: "https://api.tforum.bigmarket.ai/forum-api",
    VITE_SUI_API: "http://localhost:9001",
    VITE_MEMPOOL_API: "https://beta.sbtc-mempool.tech/api/proxy",
    VITE_POLL_PAYMENT_USTX: 50000000,
    VITE_BITCOIN_WALLET: "bcrt1q4zymxl8934vvle2ppzw0j6tkwz3d7qw4f0esme",
    VITE_CLARITY_BITCOIN:
      "ST1CV2YGRJA5X8BWS0GP31J9HF56M06CQK8998TSX.clarity-bitcoin-lib-v5",
    VITE_WALLET_CONNECT_PROJECT_ID: "085d52703daed2198b4dbc2cd815951f",
  },
  mainnet: {
    VITE_PUBLIC_APP_NAME: "BigMarket",
    VITE_PUBLIC_APP_VERSION: "1.0.0",
    VITE_NETWORK: "mainnet",
    VITE_BIGMARKET_API: "https://api.bigmarket.ai/bigmarket-api",
    VITE_BIGMARKET_WS: "https://api.bigmarket.ai/bigmarket-api/ws",
    VITE_STACKS_API: "https://api.hiro.so",
    VITE_STACKS_EXPLORER: "https://explorer.hiro.so",
    VITE_FORUM_API: "https://api.forum.bigmarket.ai/forum-api",
    VITE_SUI_API: "http://localhost:9001",
    VITE_MEMPOOL_API: "https://mempool.space/api",
    VITE_POLL_PAYMENT_USTX: 50000000,
    VITE_BITCOIN_WALLET: "bcrt1q4zymxl8934vvle2ppzw0j6tkwz3d7qw4f0esme",
    VITE_CLARITY_BITCOIN:
      "SP1SCD8ERMTFYE6CK9S0MHWQCP6SY4NAVFJ538A27.clarity-bitcoin-lib-v5",
    VITE_WALLET_CONNECT_PROJECT_ID: "085d52703daed2198b4dbc2cd815951f",
  },
};
export const daoConfigByNetwork: { [key: string]: DaoConfig } = {
  devnet: {
    VITE_DAOS: "ecosystem-dao,bigmarket-dao",
    VITE_DAO_SIP_VOTES: "bdp001-sip-021-nakamoto",
    VITE_DAO_VOTING_CONTRACTS: "bme001-0-proposal-voting",
    VITE_DAO_POX: "bme002-proposal-submission",
    VITE_DAO_SCALAR_HEDGE_STRATEGY: "bme032-0-scalar-strategy-hedge",
    VITE_NETWORK: "devnet",
    VITE_DAO_DEPLOYER: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM",
    VITE_DAO: "bigmarket-dao",
    VITE_DAO_BASE_CONTRACTS: "ecosystem-dao,bigmarket-dao",
    VITE_DAO_PROPOSAL:
      "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.bdp001-sip-021-test-01",
    VITE_DAO_PROPOSAL_VOTING_EXTENSION: "bme007-snapshot-proposal-voting",
    VITE_DAO_FUNDED_SUBMISSION_EXTENSION: "bme002-proposal-submission",
    VITE_DAO_EMERGENCY_EXECUTE_EXTENSION: "bme004-emergency-execute",
    VITE_DAO_MARKET_VOTING: "bme021-0-market-voting",
    VITE_DAO_MARKET_GATING: "bme022-0-market-gating",
    VITE_DAO_MARKET_PREDICTING: "bme024-0-market-predicting",
    VITE_DAO_MARKET_SCALAR: "bme024-0-market-scalar-pyth",
    VITE_DAO_MARKET_BITCOIN: "bme023-0-market-bitcoin",
    VITE_DAO_GOVERNANCE_TOKEN: "bme000-0-governance-token",
    VITE_DAO_TOKEN_SALE: "bme010-0-token-sale",
    VITE_DAO_CORE_PROPOSALS: "bme003-0-core-proposals",
    VITE_DAO_CORE_VOTING: "bme001-0-proposal-voting",
    VITE_DAO_TREASURY: "bme006-0-treasury",
    VITE_DAO_REPUTATION_TOKEN: "bme030-0-reputation-token",
    VITE_DAO_LIQUIDITY_CONTRIBUTION: "bme010-0-liquidity-contribution",
    VITE_DAO_RESOLUTION_COORDINATOR: "bme008-0-resolution-coordinator",
    VITE_DAO_VAULT: "bme050-0-vault",
    VITE_DAO_BIG_PLAY: "big-play",
    VITE_SBTC_DEPLOYER: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM",
    VITE_PEPE_FULL_CONTRACT: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.tpepe",
    VITE_USDH_FULL_CONTRACT: "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.tusdh",
    VITE_WRAPPED_STX_FULL_CONTRACT:
      "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.wrapped-stx",
  },
  testnet: {
    VITE_DAOS: "ecosystem-dao,bigmarket-dao",
    VITE_DAO_SIP_VOTES: "bdp001-sip-021-nakamoto",
    VITE_DAO_VOTING_CONTRACTS: "bme001-0-proposal-voting",
    VITE_DAO_POX: "bme002-proposal-submission",
    VITE_DAO_SCALAR_HEDGE_STRATEGY: "bme032-0-scalar-strategy-hedge",
    VITE_NETWORK: "testnet",
    VITE_DAO_DEPLOYER: "ST30Q4WJYHGMYEE1CTGQ334R9M7KQ8ETVQ9NB134T",
    VITE_DAO_BASE_CONTRACTS: "ecosystem-dao,bigmarket-dao",
    VITE_DAO: "bigmarket-dao",
    VITE_DAO_PROPOSAL:
      "ST1CV2YGRJA5X8BWS0GP31J9HF56M06CQK8998TSX.bdp001-sip-021-nakamoto",
    VITE_DAO_PROPOSAL_VOTING_EXTENSION: "bme007-snapshot-proposal-voting",
    VITE_DAO_FUNDED_SUBMISSION_EXTENSION: "bme008-flexible-funded-submission",
    VITE_DAO_EMERGENCY_EXECUTE_EXTENSION: "bme004-emergency-execute",
    VITE_DAO_MARKET_VOTING: "bme021-0-market-voting",
    VITE_DAO_MARKET_GATING: "bme022-0-market-gating",
    VITE_DAO_MARKET_PREDICTING: "bme024-0-market-predicting",
    VITE_DAO_MARKET_SCALAR: "bme024-0-market-scalar-pyth",
    VITE_DAO_MARKET_BITCOIN: "bme023-0-market-bitcoin",
    VITE_DAO_GOVERNANCE_TOKEN: "bme000-0-governance-token",
    VITE_DAO_TOKEN_SALE: "bme010-0-token-sale",
    VITE_DAO_CORE_PROPOSALS: "bme003-0-core-proposals",
    VITE_DAO_CORE_VOTING: "bme001-0-proposal-voting",
    VITE_DAO_TREASURY: "bme006-0-treasury",
    VITE_DAO_REPUTATION_TOKEN: "bme030-0-reputation-token",
    VITE_DAO_LIQUIDITY_CONTRIBUTION: "bme010-0-liquidity-contribution",
    VITE_DAO_RESOLUTION_COORDINATOR: "bme008-0-resolution-coordinator",
    VITE_DAO_VAULT: "bme050-0-vault",
    VITE_DAO_BIG_PLAY: "big-play",
    VITE_SBTC_DEPLOYER: "ST1F7QA2MDF17S807EPA36TSS8AMEFY4KA9TVGWXT",
    VITE_PEPE_FULL_CONTRACT: "ST1CV2YGRJA5X8BWS0GP31J9HF56M06CQK8998TSX.tpepe",
    VITE_USDH_FULL_CONTRACT: "ST1CV2YGRJA5X8BWS0GP31J9HF56M06CQK8998TSX.tusdh",
    VITE_WRAPPED_STX_FULL_CONTRACT:
      "ST1CV2YGRJA5X8BWS0GP31J9HF56M06CQK8998TSX.wrapped-stx",
  },
  mainnet: {
    VITE_DAOS: "ecosystem-dao,bigmarket-dao",
    VITE_DAO_SIP_VOTES: "bdp001-sip-021-nakamoto",
    VITE_DAO_VOTING_CONTRACTS: "bme001-0-proposal-voting",
    VITE_DAO_POX: "bme002-proposal-submission",
    VITE_DAO_SCALAR_HEDGE_STRATEGY: "bme032-0-scalar-strategy-hedge",
    VITE_NETWORK: "mainnet",
    VITE_DAO_DEPLOYER: "SP1SCD8ERMTFYE6CK9S0MHWQCP6SY4NAVFJ538A27",
    VITE_DAO_BASE_CONTRACTS: "ecosystem-dao,bigmarket-dao",
    VITE_DAO: "bigmarket-dao",
    VITE_DAO_PROPOSAL:
      "SP1SCD8ERMTFYE6CK9S0MHWQCP6SY4NAVFJ538A27.bdp001-sip-021-nakamoto",
    VITE_DAO_PROPOSAL_VOTING_EXTENSION: "bme007-snapshot-proposal-voting",
    VITE_DAO_FUNDED_SUBMISSION_EXTENSION: "bme008-flexible-funded-submission",
    VITE_DAO_EMERGENCY_EXECUTE_EXTENSION: "bme004-emergency-execute",
    VITE_DAO_MARKET_VOTING: "bme021-0-market-voting",
    VITE_DAO_MARKET_GATING: "bme022-0-market-gating",
    VITE_DAO_MARKET_PREDICTING: "bme024-0-market-predicting",
    VITE_DAO_MARKET_SCALAR: "bme024-0-market-scalar-pyth",
    VITE_DAO_MARKET_BITCOIN: "bme023-0-market-bitcoin",
    VITE_DAO_GOVERNANCE_TOKEN: "bme000-0-governance-token",
    VITE_DAO_TOKEN_SALE: "bme010-0-token-sale",
    VITE_DAO_CORE_PROPOSALS: "bme003-0-core-proposals",
    VITE_DAO_CORE_VOTING: "bme001-0-proposal-voting",
    VITE_DAO_TREASURY: "bme006-0-treasury",
    VITE_DAO_REPUTATION_TOKEN: "bme030-0-reputation-token",
    VITE_DAO_LIQUIDITY_CONTRIBUTION: "bme010-0-liquidity-contribution",
    VITE_DAO_RESOLUTION_COORDINATOR: "bme008-0-resolution-coordinator",
    VITE_DAO_VAULT: "bme050-0-vault",
    VITE_DAO_BIG_PLAY: "big-play",
    VITE_SBTC_DEPLOYER: "SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4",
    VITE_PEPE_FULL_CONTRACT: "SP1SCD8ERMTFYE6CK9S0MHWQCP6SY4NAVFJ538A27.tpepe",
    VITE_USDH_FULL_CONTRACT: "SP1SCD8ERMTFYE6CK9S0MHWQCP6SY4NAVFJ538A27.tusdh",
    VITE_WRAPPED_STX_FULL_CONTRACT:
      "SP1SCD8ERMTFYE6CK9S0MHWQCP6SY4NAVFJ538A27.wrapped-stx",
  },
};
