/**
 * TypeScript design tokens — mirror of `theme.css`. Runtime truth is `theme.css`.
 * Update both together. See `docs-v2/tokens-and-rules.lock.md`.
 */
export const tokens = {
  light: {
    colors: {
      background: 'var(--color-surface-50)',
      foreground: 'var(--color-surface-950)',
      card: 'var(--color-surface-50)',
      cardForeground: 'var(--color-surface-950)',
      popover: '#fff',
      popoverForeground: 'var(--color-surface-950)',
      muted: 'var(--color-surface-100)',
      mutedForeground: 'var(--color-surface-700)',
      border: 'var(--color-surface-200)',
      /** Input BORDER color (shadcn convention). */
      input: 'var(--color-surface-200)',
      overlay: 'rgba(0, 0, 0, 0.4)',
      primary: 'var(--color-primary-500)',
      primaryForeground: 'var(--color-primary-contrast-500)',
      secondary: 'var(--color-surface-200)',
      secondaryForeground: 'var(--color-surface-900)',
      accent: 'var(--color-secondary-500)',
      accentForeground: 'var(--color-secondary-contrast-500)',
      destructive: 'var(--color-error-500)',
      destructiveForeground: 'var(--color-error-contrast-500)',
      success: 'var(--color-success-500)',
      warning: 'var(--color-warning-500)',
      info: 'var(--color-secondary-500)',
      community: 'var(--color-tertiary-500)',
      priceUp: 'var(--color-success-500)',
      priceDown: 'var(--color-error-500)',
      priceNeutral: 'var(--color-muted-foreground)',
      liveIndicator: 'var(--color-error-500)',
      selected: 'var(--color-secondary-500)',
      outcome1: 'var(--color-warning-500)',
      outcome2: 'var(--color-success-500)',
      outcome3: 'var(--color-secondary-500)',
      outcome4: 'var(--color-tertiary-500)',
      ring: 'var(--color-secondary-400)',
    },
  },
  dark: {
    colors: {
      background: 'var(--color-surface-950)',
      foreground: 'var(--color-surface-50)',
      card: 'var(--color-surface-900)',
      cardForeground: 'var(--color-surface-50)',
      popover: 'var(--color-surface-900)',
      popoverForeground: 'var(--color-surface-50)',
      muted: 'var(--color-surface-900)',
      mutedForeground: 'var(--color-surface-300)',
      border: 'var(--color-surface-800)',
      /** Input BORDER color (shadcn convention). */
      input: 'var(--color-surface-800)',
      overlay: 'rgba(0, 0, 0, 0.65)',
      primary: 'var(--color-primary-400)',
      primaryForeground: 'var(--color-primary-contrast-400)',
      secondary: 'var(--color-surface-800)',
      secondaryForeground: 'var(--color-surface-50)',
      accent: 'var(--color-secondary-400)',
      accentForeground: 'var(--color-secondary-contrast-400)',
      destructive: 'var(--color-error-400)',
      destructiveForeground: 'var(--color-error-contrast-400)',
      success: 'var(--color-success-400)',
      warning: 'var(--color-warning-400)',
      info: 'var(--color-secondary-400)',
      community: 'var(--color-tertiary-400)',
      priceUp: 'var(--color-success-400)',
      priceDown: 'var(--color-error-400)',
      priceNeutral: 'var(--color-muted-foreground)',
      liveIndicator: 'var(--color-error-400)',
      selected: 'var(--color-secondary-400)',
      outcome1: 'var(--color-warning-400)',
      outcome2: 'var(--color-success-400)',
      outcome3: 'var(--color-secondary-400)',
      outcome4: 'var(--color-tertiary-400)',
      ring: 'var(--color-secondary-300)',
    },
  },
  radius: {
    sm: 'var(--radius-base)',
    md: 'var(--radius-md)',
    lg: 'var(--radius-lg)',
    xl: 'var(--radius-container)',
  },
  spacing: {
    xs: '4px',
    sm: '8px',
    md: '16px',
    lg: '24px',
    xl: '32px',
  },
  typography: {
    fontFamily: {
      sans: 'system-ui, sans-serif',
      heading:
        "Bahnschrift, 'DIN Alternate', 'Franklin Gothic Medium', 'Nimbus Sans Narrow', sans-serif-condensed, sans-serif",
    },
    fontSize: {
      xs: '12px',
      sm: '14px',
      base: '16px',
      lg: '18px',
      xl: '24px',
    },
  },
} as const;
