export interface AppConfig {
  VITE_PUBLIC_APP_NAME: string;
  VITE_PUBLIC_APP_VERSION: string;
  VITE_NETWORK: string;
  VITE_POLL_PAYMENT_USTX: number;
  VITE_BIGMARKET_API: string;
  VITE_BIGMARKET_WS: string;
  VITE_SUI_API: string;
  VITE_FORUM_API: string;
  VITE_STACKS_API: string;
  VITE_STACKS_EXPLORER: string;
  VITE_MEMPOOL_API: string;
  VITE_BITCOIN_WALLET: string;
  VITE_CLARITY_BITCOIN: string;
  VITE_WALLET_CONNECT_PROJECT_ID: string;
}
export type Network = "devnet" | "testnet" | "mainnet";
export interface DaoConfig {
  VITE_NETWORK: string;
  VITE_DAO_DEPLOYER: string;
  VITE_DAO_BASE_CONTRACTS: string;
  VITE_DAO: string;
  VITE_DAO_PROPOSAL: string;
  VITE_DAO_MARKET_VOTING: string;
  VITE_DAO_MARKET_GATING: string;
  VITE_DAO_MARKET_PREDICTING: string;
  VITE_DAO_MARKET_SCALAR: string;
  VITE_DAO_MARKET_BITCOIN: string;
  VITE_DAO_CORE_PROPOSALS: string;
  VITE_DAO_CORE_VOTING: string;
  VITE_DAO_TREASURY: string;
  VITE_DAO_GOVERNANCE_TOKEN: string;
  VITE_DAO_TOKEN_SALE: string;
  VITE_DAO_PROPOSAL_VOTING_EXTENSION: string;
  VITE_DAO_FUNDED_SUBMISSION_EXTENSION: string;
  VITE_DAO_EMERGENCY_EXECUTE_EXTENSION: string;
  VITE_DAO_REPUTATION_TOKEN: string;
  VITE_DAO_BIG_PLAY: string;
  VITE_DAO_LIQUIDITY_CONTRIBUTION: string;
  VITE_DAO_RESOLUTION_COORDINATOR: string;
  VITE_SBTC_DEPLOYER: string;
  VITE_PEPE_FULL_CONTRACT: string;
  VITE_USDH_FULL_CONTRACT: string;
  VITE_WRAPPED_STX_FULL_CONTRACT: string;
}
